publicHost: llm.private-llm.shop
publicScheme: https
contentPath: /pm-content.json
branding:
  sidebar:
    title: "LLM by MODEL Corp"
  marketplace:
    title: "LLM Service"
    description: "LLM services provided by MODEL Corp."
