apiVersion: kro.run/v1alpha1
kind: ResourceGraphDefinition
metadata:
  name: {{ .Values.component.name }}
spec:
  schema:
    apiVersion: v1alpha1
    kind: PrivateLlmOperatorRelease
  resources:
    - id: ns
      template:
        apiVersion: v1
        kind: Namespace
        metadata:
          name: {{ .Values.operator.targetNamespace }}

    # Fetch Helm chart resource from the OCM component
    - id: resourceChart
      template:
        apiVersion: delivery.ocm.software/v1alpha1
        kind: Resource
        metadata:
          name: {{ .Values.component.name }}-helm-resource
          namespace: {{ .Values.component.namespace }}
        spec:
          componentRef:
            name: {{ .Values.component.name }}
          resource:
            byReference:
              resource:
                name: oci-helm-chart-private-llm-operator
                version: {{ trimPrefix "v" .Values.component.semver | quote }}
          additionalStatusFields:
            registry: resource.access.imageReference.toOCI().registry
            repository: resource.access.imageReference.toOCI().repository
            tag: resource.access.imageReference.toOCI().tag
          interval: {{ .Values.component.interval }}
          ocmConfig:
            - kind: Repository
              apiVersion: delivery.ocm.software/v1alpha1
              name: {{ .Values.component.repositoryRefName }}
              namespace: {{ .Values.component.repositoryRefNamespace }}

    # Fetch operator image resource from the OCM component and split reference
    - id: resourceImage
      template:
        apiVersion: delivery.ocm.software/v1alpha1
        kind: Resource
        metadata:
          name: {{ .Values.component.name }}-image-resource
          namespace: {{ .Values.component.namespace }}
        spec:
          componentRef:
            name: {{ .Values.component.name }}
          resource:
            byReference:
              resource:
                name: private-llm-image
                version: {{ trimPrefix "v" .Values.component.semver | quote }}
          additionalStatusFields:
            registry: resource.access.imageReference.toOCI().registry
            repository: resource.access.imageReference.toOCI().repository
            tag: resource.access.imageReference.toOCI().tag
          interval: {{ .Values.component.interval }}
          ocmConfig:
            - kind: Repository
              apiVersion: delivery.ocm.software/v1alpha1
              name: {{ .Values.component.repositoryRefName }}
              namespace: {{ .Values.component.repositoryRefNamespace }}

    - id: ocirepository
      template:
        apiVersion: source.toolkit.fluxcd.io/v1
        kind: OCIRepository
        metadata:
          name: ${ns.metadata.name}-private-llm-operator
          namespace: ${ns.metadata.name}
        spec:
          interval: {{ .Values.component.interval }}
          layerSelector:
            mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
            operation: copy
          url: oci://${resourceChart.status.additional.?registry}/${resourceChart.status.additional.?repository}
          ref:
            tag: ${resourceChart.status.additional.?tag}
          secretRef:
            name: {{ .Values.operator.imagePullSecretName }}

    - id: helmrelease
      template:
        apiVersion: helm.toolkit.fluxcd.io/v2
        kind: HelmRelease
        metadata:
          name: ${ns.metadata.name}-private-llm-operator
          namespace: ${ns.metadata.name}
        spec:
          interval: {{ .Values.component.interval }}
          releaseName: ${ns.metadata.name}-private-llm-operator
          targetNamespace: ${ns.metadata.name}
          install:
            createNamespace: true
          chartRef:
            kind: OCIRepository
            name: ${ocirepository.metadata.name}
            namespace: ${ns.metadata.name}
          values:
            PUBLIC_HOST: {{ .Values.operator.publicHost }}
            PUBLIC_SCHEME: {{ .Values.operator.publicScheme }}
            tls:
              secretName: {{ .Values.operator.tlsSecretName | quote }}
            image:
              repository: ${resourceImage.status.additional.?registry}/${resourceImage.status.additional.?repository}
              tag: ${resourceImage.status.additional.?tag}
              pullPolicy: {{ .Values.operator.imagePullPolicy }}
            imagePullSecrets:
              - name: {{ .Values.operator.imagePullSecretName }}
            traefik:
              enabled: {{ .Values.operator.traefikEnabled }}
              service:
                type: {{ .Values.operator.traefikServiceType }}
              ports:
                web:
                  nodePort: {{ .Values.operator.traefikNodePortWeb }}
                websecure:
                  nodePort: {{ .Values.operator.traefikNodePortWebsecure }}
            ingress:
              {{- if .Values.operator.ingressExtraAnnotations }}
              extraAnnotations:
                {{- toYaml .Values.operator.ingressExtraAnnotations | nindent 16 }}
              {{- else }}
              extraAnnotations: {}
              {{- end }}

