{{- if .Values.publishedResources.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: api-syncagent:privatellm
  labels:
    app.kubernetes.io/name: private-llm-sync-agent
    app.kubernetes.io/component: portal-integration
rules:
  - apiGroups:
      - llm.privatellms.msp
    resources:
      - llminstances
      - apitokenrequests
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete

  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: api-syncagent:privatellm
  labels:
    app.kubernetes.io/name: private-llm-sync-agent
    app.kubernetes.io/component: portal-integration
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: api-syncagent:privatellm
subjects:
  - kind: ServiceAccount
    name: {{ .Values.publishedResources.serviceAccountName | default .Release.Name }}
    namespace: {{ .Values.publishedResources.namespace | default .Release.Namespace }}
{{- end }}


