{{- if .Values.publishedResources.enabled }}
apiVersion: syncagent.kcp.io/v1alpha1
kind: PublishedResource
metadata:
  name: publish-llm-llminstances
  namespace: {{ .Values.publishedResources.namespace | default .Release.Namespace }}
  labels:
    app.kubernetes.io/name: private-llm-sync-agent
    app.kubernetes.io/component: portal-integration
spec:
  resource:
    kind: LLMInstance
    apiGroup: llm.privatellms.msp
    version: v1alpha1
  naming:
    namespace: "{{`{{ .ClusterName }}`}}"
    name: "{{`{{ .Object.metadata.name }}`}}"
---
apiVersion: syncagent.kcp.io/v1alpha1
kind: PublishedResource
metadata:
  name: publish-llm-apitokenrequests
  namespace: {{ .Values.publishedResources.namespace | default .Release.Namespace }}
  labels:
    app.kubernetes.io/name: private-llm-sync-agent
    app.kubernetes.io/component: portal-integration
spec:
  resource:
    kind: APITokenRequest
    apiGroup: llm.privatellms.msp
    version: v1alpha1
  naming:
    namespace: "{{`{{ .ClusterName }}`}}"
    name: "{{`{{ .Object.metadata.name }}`}}"
  related:
    - identifier: token-secret
      origin: service
      kind: Secret
      object:
        reference:
          path: status.secretName
{{- end }}

