general:
  buildTool: 'docker'
  productiveBranch: 'main'
  vaultPath: 'piper/sap-project-apeirora'
  vaultBasePath: 'piper/sap-project-apeirora'
  vaultPipelineName: 'showroom-private-llm'
  vaultServerUrl: 'https://vault.tools.sap'
  vaultNamespace: 'ies/hyperspace/pipelines'
  nativeBuild: true
stages:
  Release:
    sapDownloadArtifact: false
  Post:
    # Secret rotation handled by Hyperspace Portal, enabling it back might cause unintended behavior
    vaultRotateSecretId: false
steps:
  sapCallStagingService:
    url: 'https://staging.repositories.cloud.sap/stage/api'
    profile: 'group-apeirora-l29mw-default'
  kanikoExecute:
    containerImageName: 'showroom-private-llm'
  sapCumulusUpload:
    pipelineId: '52dc9a51-0b50-43aa-972e-10f225115c7e'
