apiVersion: kro.run/v1alpha1
kind: PrivateLlmOperatorRelease
metadata:
  name: private-llm-operator-instance
spec:
  targetNamespace: private-llm-system
  publicHost: localhost
  publicScheme: http
  imagePullSecretName: ghcr-credentials
  traefikEnabled: true
  traefikServiceType: NodePort
  traefikNodePortWeb: 30080
  traefikNodePortWebsecure: 30443
  tlsSecretName: ""


