component:
  name: private-llm-operator
  namespace: ocm-system # fix: cannot be changed
  componentName: llm.privatellms.msp/private-llm
  repositoryUrl: ghcr.io/apeirora/ocm
  secretRefName: ghcr-credentials
  semver: ">=2.0.1"
  interval: 1m

operator:
  targetNamespace: private-llm-operator
  publicHost: localhost
  publicScheme: http
  imagePullSecretName: ghcr-credentials
  imagePullPolicy: IfNotPresent
  traefikEnabled: true
  traefikServiceType: LoadBalancer
  traefikNodePortWeb: 30080
  traefikNodePortWebsecure: 30443
  tlsSecretName: ""
  ingressExtraAnnotations: {}
