apiVersion: apis.kcp.io/v1alpha1
kind: APIExport
metadata:
  name: llm.privatellms.msp
  labels:
    ui.platform-mesh.io/content-for: llm.privatellms.msp
spec:
  permissionClaims:
    - group: ""
      resource: namespaces
      all: true
    - group: ""
      resource: events
      all: true
    - group: ""
      resource: secrets
      all: true
