{{- $marketplaceTitle := .Values.branding.marketplace.title -}}
{{- $marketplaceDescription := .Values.branding.marketplace.description -}}
apiVersion: ui.platform-mesh.io/v1alpha1
kind: ProviderMetadata
metadata:
  name: llm.privatellms.msp
spec:
  displayName: {{ $marketplaceTitle | quote }}
  description: |
{{ $marketplaceDescription | nindent 4 }}
  contacts:
    - displayName: Alex IT Architect
      role: ["IT Architect"]
  preferredSupportChannels:
    - displayName: ApeiroRA Help Desk
      url: https://help.privatellms.msp
  icon:
    light:
      data: 'data:image/png;base64,{{ (.Files.Get "files/icon.png") | b64enc }}'
    dark:
      data: 'data:image/png;base64,{{ (.Files.Get "files/icon.png") | b64enc }}'
