apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUQ1akNDQWs2Z0F3SUJBZ0lRQTJLTjQ4WWU1d2VudVZVWWFHY3IrVEFOQmdrcWhraUc5dzBCQVFzRkFEQU4KTVFzd0NRWURWUVFERXdKallUQWVGdzB5TmpBeE1qWXhNelE0TVROYUZ3MHpOakF4TWpZeE16UTVNVE5hTUEweApDekFKQmdOVkJBTVRBbU5oTUlJQm9qQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FZOEFNSUlCaWdLQ0FZRUF0d3BFCk9DdkVMZlAzTVZCalZrNWxQYjRPWG5Vc3l1M3huR2hpVzdMc1pQeFgyZHNZbGZVaGNBRHZvWFQ0c3FvT0ZDYWYKRFY5V2hMZ2dGcXNkOGR0ZnBjSUJKWi9IN2RRckdLdW9weGZaaG5NUm96dTViQnllaUtJb1UrOXdZZGVId00wSAplcFVnZHl5bzNyUG5GUzMrVXVqQjBXSGtaSXRkZTJFSVZLTGxlajlYaDNYNHFScTZXR0ZBRDJEQkZ3aWhweWV5Cmc3bXdqczBBRUdwSDFlckxvaHNaenFqWDZJdC91SlNpN2tiUTJmU0VQeFlRVmNwdjhCSVJuRmI1T3FGSTVJbTQKeEFBMWpSR29pN1BaKzJHN2VaeFdsSENzNWROemxmRGlHQmFUMWNORm9KZnlxQ0I1bm9ZMjc0TkRkM0NXTUhoOQo1dVFxcm9wZEhEMzJTaXFROVFwM05uSldVd0pIQXU4ejEvZGxoUDk2WFZNY3lRZ1MzS2lDZWthRUlMVGtNWitCCnY2enRHdHN3TDkvVkUram1uOUQvazlZVUM3d202YmNPeTByNWtSRU9nQi9CVjFSWDNRYm5NenRoSVhndG1SVk4KaUJGUEFZOFFCU2hkTG9tb256dDE3UjJ6d3hORGlGTnpXNkovVXFUS2gyT3ltbEkxUGxnM1lCQnRWU1VYQWdNQgpBQUdqUWpCQU1BNEdBMVVkRHdFQi93UUVBd0lCcGpBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXCkJCVEIxREt3SzdXMHZVcjJPM0hZbksyNFNvVjdxakFOQmdrcWhraUc5dzBCQVFzRkFBT0NBWUVBa3hHZS9qMEEKMUhiRkNjdk5xQWFOL0p2ZStqOWNwcEs0NVpBdjVyaVplVDcxZ1dZTzI5d1lKcUFrbVhrbWdqcExiMUZqd0xIaAprckVobnNjbmdJTEJwYnJLWHBlLzJyNllUSlZ1K3U0MWZTNGh6NFluS0g4UXhmakhTNFF1K2VFYVE4MUFRZTJ0CnVIS2I1cDIxM2NzMTlMOWVmbjVvNWtPUFJoRTdHM2x0R3MvRWJYUldsbWZMOVVpUkdjWkpVMHkyZkJOa2pvbmsKWm54ZVBod2JOb0pKWklJUzQ4a0ZIWXFTYXVVNGJGd0RyQkFmNmxEL2tlUVExTnpZOUc5YUtVemwzRVZpeCtaYgpwZjBOclhzU29BLzlLUXlmeXMzdDljWVZPTE5iNDRLRmJEMDJPSHNDRVY0U1dQbmFCR2hhOHNmNmRDcGdHWFY5Cjd2a1p4NWlTYjBLUjc5YUE0QlNWYnh6Y0hubERPcktDMzFOa2ZzcktIR21LdTNpODlpZFpEckV3MzNnTllyZEMKNVVpYmFiV2cwNWFRYVp6SzlEdWpudTdyWCtLOTVoQjY1WmxCVGx6dWpzOCthTTlraVBmRCtRT0JsTkVmZ084Ngp3NGJJT2dERGJTMm50TzZILzZrN1k5czhFb3ZkSU1DSjM2VG9DaWxCMWZwVjFoV0oxbDBENDJkTgotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    extensions:
    - extension:
        gardenClusterIdentity: landscape-apeirora-one
        shootRef:
          name: msp02
          namespace: garden-pm-cc-d2
      name: client.authentication.k8s.io/exec
    server: https://api.msp02.pm-cc-d2.shoot.gardener.cc-one.showroom.apeirora.eu
  name: garden-pm-cc-d2--msp02-external
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUQ1akNDQWs2Z0F3SUJBZ0lRQTJLTjQ4WWU1d2VudVZVWWFHY3IrVEFOQmdrcWhraUc5dzBCQVFzRkFEQU4KTVFzd0NRWURWUVFERXdKallUQWVGdzB5TmpBeE1qWXhNelE0TVROYUZ3MHpOakF4TWpZeE16UTVNVE5hTUEweApDekFKQmdOVkJBTVRBbU5oTUlJQm9qQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FZOEFNSUlCaWdLQ0FZRUF0d3BFCk9DdkVMZlAzTVZCalZrNWxQYjRPWG5Vc3l1M3huR2hpVzdMc1pQeFgyZHNZbGZVaGNBRHZvWFQ0c3FvT0ZDYWYKRFY5V2hMZ2dGcXNkOGR0ZnBjSUJKWi9IN2RRckdLdW9weGZaaG5NUm96dTViQnllaUtJb1UrOXdZZGVId00wSAplcFVnZHl5bzNyUG5GUzMrVXVqQjBXSGtaSXRkZTJFSVZLTGxlajlYaDNYNHFScTZXR0ZBRDJEQkZ3aWhweWV5Cmc3bXdqczBBRUdwSDFlckxvaHNaenFqWDZJdC91SlNpN2tiUTJmU0VQeFlRVmNwdjhCSVJuRmI1T3FGSTVJbTQKeEFBMWpSR29pN1BaKzJHN2VaeFdsSENzNWROemxmRGlHQmFUMWNORm9KZnlxQ0I1bm9ZMjc0TkRkM0NXTUhoOQo1dVFxcm9wZEhEMzJTaXFROVFwM05uSldVd0pIQXU4ejEvZGxoUDk2WFZNY3lRZ1MzS2lDZWthRUlMVGtNWitCCnY2enRHdHN3TDkvVkUram1uOUQvazlZVUM3d202YmNPeTByNWtSRU9nQi9CVjFSWDNRYm5NenRoSVhndG1SVk4KaUJGUEFZOFFCU2hkTG9tb256dDE3UjJ6d3hORGlGTnpXNkovVXFUS2gyT3ltbEkxUGxnM1lCQnRWU1VYQWdNQgpBQUdqUWpCQU1BNEdBMVVkRHdFQi93UUVBd0lCcGpBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXCkJCVEIxREt3SzdXMHZVcjJPM0hZbksyNFNvVjdxakFOQmdrcWhraUc5dzBCQVFzRkFBT0NBWUVBa3hHZS9qMEEKMUhiRkNjdk5xQWFOL0p2ZStqOWNwcEs0NVpBdjVyaVplVDcxZ1dZTzI5d1lKcUFrbVhrbWdqcExiMUZqd0xIaAprckVobnNjbmdJTEJwYnJLWHBlLzJyNllUSlZ1K3U0MWZTNGh6NFluS0g4UXhmakhTNFF1K2VFYVE4MUFRZTJ0CnVIS2I1cDIxM2NzMTlMOWVmbjVvNWtPUFJoRTdHM2x0R3MvRWJYUldsbWZMOVVpUkdjWkpVMHkyZkJOa2pvbmsKWm54ZVBod2JOb0pKWklJUzQ4a0ZIWXFTYXVVNGJGd0RyQkFmNmxEL2tlUVExTnpZOUc5YUtVemwzRVZpeCtaYgpwZjBOclhzU29BLzlLUXlmeXMzdDljWVZPTE5iNDRLRmJEMDJPSHNDRVY0U1dQbmFCR2hhOHNmNmRDcGdHWFY5Cjd2a1p4NWlTYjBLUjc5YUE0QlNWYnh6Y0hubERPcktDMzFOa2ZzcktIR21LdTNpODlpZFpEckV3MzNnTllyZEMKNVVpYmFiV2cwNWFRYVp6SzlEdWpudTdyWCtLOTVoQjY1WmxCVGx6dWpzOCthTTlraVBmRCtRT0JsTkVmZ084Ngp3NGJJT2dERGJTMm50TzZILzZrN1k5czhFb3ZkSU1DSjM2VG9DaWxCMWZwVjFoV0oxbDBENDJkTgotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    extensions:
    - extension:
        gardenClusterIdentity: landscape-apeirora-one
        shootRef:
          name: msp02
          namespace: garden-pm-cc-d2
      name: client.authentication.k8s.io/exec
    server: https://api.msp02.pm-cc-d2.internal.gardener.cc-one.showroom.apeirora.eu
  name: garden-pm-cc-d2--msp02-internal
contexts:
- context:
    cluster: garden-pm-cc-d2--msp02-external
    namespace: default
    user: garden-pm-cc-d2--msp02
  name: garden-pm-cc-d2--msp02-external
- context:
    cluster: garden-pm-cc-d2--msp02-internal
    namespace: default
    user: garden-pm-cc-d2--msp02
  name: garden-pm-cc-d2--msp02-internal
current-context: garden-pm-cc-d2--msp02-external
kind: Config
preferences: {}
users:
- name: garden-pm-cc-d2--msp02
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1
      args:
      - get-client-certificate
      command: kubectl-gardenlogin
      env: null
      installHint: Follow the instructions on https://github.com/gardener/gardenlogin#installation
        to install gardenlogin
      interactiveMode: IfAvailable
      provideClusterInfo: true
