apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUQ1akNDQWs2Z0F3SUJBZ0lRR1hOOHlCL3kwMlZURXIvMXRNNmJOREFOQmdrcWhraUc5dzBCQVFzRkFEQU4KTVFzd0NRWURWUVFERXdKallUQWVGdzB5TmpBeE1qWXhNelE0TVRKYUZ3MHpOakF4TWpZeE16UTVNVEphTUEweApDekFKQmdOVkJBTVRBbU5oTUlJQm9qQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FZOEFNSUlCaWdLQ0FZRUEwTXJQCkZPMWJvQ1dyVG5hSExPUnU0eWNQNmZtd3RZQ2NReW1kUmVrOHVSUUNLdCt6WnM5UFoydG1Bc3U5UytZRWpzYUUKYytmVStKV2xGZGg5QUVsc0R5UWxWSFNxdkE4RlZld2drSzNXbW1jQlY5TnVKellWbVk4aG5ZRmtZK0ZnejBVcAp6ZkJkSHVQQ1pEbm4wbDBvUUZmNk95WVdhM1NaOHFCOVQ2anhLWi9RNWRvVS92NW9FcU5RUGpFaFh6VG43MUk4CkV4RzRpK2tQOVRZU2I0OXpIZktsZjNFbk9RZFVTRE0zaHNpQzFjTFZDK29rUkRDUDBSekptelZ6S3BtSzgzQnMKNWplN2FtY3M1U3hqdkljcUpJN01qZHNGaDlwWHo4cVN1eWRoRE1oNnhSeUthQkRJMGVmNkxTZHZvRFBidTZhaApXZGMxTDA3MmlDV3diU0h3V0JYbVJtWkwrL3c4M1hZcG9BTkExM2MzT1BYSlI4cW9zZGx1RzZGdmNwRmtNYTlECldVV2FGUllxUXU1OEV1M0hmelRJSVlVUyt0NkJkTWpadjJDZ280NW91RHRQdGNEdVYzSDA1OVJvY2NZKzdBOEcKNi8vMHQ4dXVOZWlXTFdKRDZuWDJ6bzF0S0JZMjZMM3FiUTZiOVlzRGxPbURtWmJmS0V6OGhJR3dxVEFIQWdNQgpBQUdqUWpCQU1BNEdBMVVkRHdFQi93UUVBd0lCcGpBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXCkJCUml1SURINWhRVEhKYkZab3J1VzVKMG44SlMyVEFOQmdrcWhraUc5dzBCQVFzRkFBT0NBWUVBVEZuYUsvdHQKeFR4SU1DYTZOd0RVK1Vxcm9RS1NPZnRheU1aeThrTHprQWZ1QVdlYUdDNkF4Vks4SXdaV2h3MzZCTi9JOWVyTQpEbEkxM2k0ZmlObVBlRmJkN0sxQ3lXbzhDc0xEYXJhL1JxNFFOTTZaM1hRK3pCaE1vNU5sR2p2NzhnRFl5VVhlCkhRZ3hwTmlyUWpRQi9uTU1abGdyS3NFNno2VGMxLzJ2UHV3eU9BZFdjZjZ6YVpNTVMwVDRMNmNNNEE5dS9nZTYKbFlYZWVmUHc0bnV3WnJFZW5CNHc5bGYyZ2tsRVNqcjJDQWRuSStpNUFtOGJWVW5IbXhxV2dyRGg3Uit6NjVFdwpnQi9JNzBwaVQySDR1em9ScXpsdTArVmR2c3N3Y0diaVpDdUxIKzJpc0d5eTdYSERpN0oxaDc0QTJLRVZtSlErCm80TmJRdVRYS012WDNUaHlGOWRRakdGY0N1a1BEVU9VWmJzWGx2OFdrWldSWFRMa3I4SUdVUld4U1c5OVdHd2kKVnlYZWhDaUZ5d0QySjZLcmNaK0ZOV05CQkttUXM3U3VGOE9pTXNxVWd6dlZZZWgwbUpXQkloOXVac09wRThCeQpYM3JwM0pESGsvTVpoNVVqRWxQRXZkTUp1RHord0RUWnoxTDl5c1VGSDZLcyt6VFVyRW4yQkt0aAotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    extensions:
    - extension:
        gardenClusterIdentity: landscape-apeirora-one
        shootRef:
          name: msp01
          namespace: garden-pm-cc-d2
      name: client.authentication.k8s.io/exec
    server: https://api.msp01.pm-cc-d2.shoot.gardener.cc-one.showroom.apeirora.eu
  name: garden-pm-cc-d2--msp01-external
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUQ1akNDQWs2Z0F3SUJBZ0lRR1hOOHlCL3kwMlZURXIvMXRNNmJOREFOQmdrcWhraUc5dzBCQVFzRkFEQU4KTVFzd0NRWURWUVFERXdKallUQWVGdzB5TmpBeE1qWXhNelE0TVRKYUZ3MHpOakF4TWpZeE16UTVNVEphTUEweApDekFKQmdOVkJBTVRBbU5oTUlJQm9qQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FZOEFNSUlCaWdLQ0FZRUEwTXJQCkZPMWJvQ1dyVG5hSExPUnU0eWNQNmZtd3RZQ2NReW1kUmVrOHVSUUNLdCt6WnM5UFoydG1Bc3U5UytZRWpzYUUKYytmVStKV2xGZGg5QUVsc0R5UWxWSFNxdkE4RlZld2drSzNXbW1jQlY5TnVKellWbVk4aG5ZRmtZK0ZnejBVcAp6ZkJkSHVQQ1pEbm4wbDBvUUZmNk95WVdhM1NaOHFCOVQ2anhLWi9RNWRvVS92NW9FcU5RUGpFaFh6VG43MUk4CkV4RzRpK2tQOVRZU2I0OXpIZktsZjNFbk9RZFVTRE0zaHNpQzFjTFZDK29rUkRDUDBSekptelZ6S3BtSzgzQnMKNWplN2FtY3M1U3hqdkljcUpJN01qZHNGaDlwWHo4cVN1eWRoRE1oNnhSeUthQkRJMGVmNkxTZHZvRFBidTZhaApXZGMxTDA3MmlDV3diU0h3V0JYbVJtWkwrL3c4M1hZcG9BTkExM2MzT1BYSlI4cW9zZGx1RzZGdmNwRmtNYTlECldVV2FGUllxUXU1OEV1M0hmelRJSVlVUyt0NkJkTWpadjJDZ280NW91RHRQdGNEdVYzSDA1OVJvY2NZKzdBOEcKNi8vMHQ4dXVOZWlXTFdKRDZuWDJ6bzF0S0JZMjZMM3FiUTZiOVlzRGxPbURtWmJmS0V6OGhJR3dxVEFIQWdNQgpBQUdqUWpCQU1BNEdBMVVkRHdFQi93UUVBd0lCcGpBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXCkJCUml1SURINWhRVEhKYkZab3J1VzVKMG44SlMyVEFOQmdrcWhraUc5dzBCQVFzRkFBT0NBWUVBVEZuYUsvdHQKeFR4SU1DYTZOd0RVK1Vxcm9RS1NPZnRheU1aeThrTHprQWZ1QVdlYUdDNkF4Vks4SXdaV2h3MzZCTi9JOWVyTQpEbEkxM2k0ZmlObVBlRmJkN0sxQ3lXbzhDc0xEYXJhL1JxNFFOTTZaM1hRK3pCaE1vNU5sR2p2NzhnRFl5VVhlCkhRZ3hwTmlyUWpRQi9uTU1abGdyS3NFNno2VGMxLzJ2UHV3eU9BZFdjZjZ6YVpNTVMwVDRMNmNNNEE5dS9nZTYKbFlYZWVmUHc0bnV3WnJFZW5CNHc5bGYyZ2tsRVNqcjJDQWRuSStpNUFtOGJWVW5IbXhxV2dyRGg3Uit6NjVFdwpnQi9JNzBwaVQySDR1em9ScXpsdTArVmR2c3N3Y0diaVpDdUxIKzJpc0d5eTdYSERpN0oxaDc0QTJLRVZtSlErCm80TmJRdVRYS012WDNUaHlGOWRRakdGY0N1a1BEVU9VWmJzWGx2OFdrWldSWFRMa3I4SUdVUld4U1c5OVdHd2kKVnlYZWhDaUZ5d0QySjZLcmNaK0ZOV05CQkttUXM3U3VGOE9pTXNxVWd6dlZZZWgwbUpXQkloOXVac09wRThCeQpYM3JwM0pESGsvTVpoNVVqRWxQRXZkTUp1RHord0RUWnoxTDl5c1VGSDZLcyt6VFVyRW4yQkt0aAotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    extensions:
    - extension:
        gardenClusterIdentity: landscape-apeirora-one
        shootRef:
          name: msp01
          namespace: garden-pm-cc-d2
      name: client.authentication.k8s.io/exec
    server: https://api.msp01.pm-cc-d2.internal.gardener.cc-one.showroom.apeirora.eu
  name: garden-pm-cc-d2--msp01-internal
contexts:
- context:
    cluster: garden-pm-cc-d2--msp01-external
    namespace: default
    user: garden-pm-cc-d2--msp01
  name: garden-pm-cc-d2--msp01-external
- context:
    cluster: garden-pm-cc-d2--msp01-internal
    namespace: default
    user: garden-pm-cc-d2--msp01
  name: garden-pm-cc-d2--msp01-internal
current-context: garden-pm-cc-d2--msp01-external
kind: Config
preferences: {}
users:
- name: garden-pm-cc-d2--msp01
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1
      args:
      - get-client-certificate
      command: kubectl-gardenlogin
      env: null
      installHint: Follow the instructions on https://github.com/gardener/gardenlogin#installation
        to install gardenlogin
      interactiveMode: IfAvailable
      provideClusterInfo: true
