apiVersion: v2
name: private-llm-operator
description: Helm chart for private-llm operator
type: application
version: 2.6.4
appVersion: 2.6.4
dependencies:
  - name: traefik
    version: 25.x.x
    repository: https://traefik.github.io/charts
    condition: traefik.enabled
