PUBLIC_HOST: localhost
PUBLIC_SCHEME: http
tls:
  secretName: ''
ocm:
  enabled: true
auth:
  externalURL: ''
image:
  repository: ghcr.io/apeirora/private-llm-controller
  tag: 2.10.2
  pullPolicy: IfNotPresent
imagePullSecrets: []
extraEnv: []
traefik:
  enabled: true
  ingressClass:
    enabled: true
    isDefaultClass: false
    name: traefik
  service:
    type: LoadBalancer
ingress:
  className: ''
  extraAnnotations: {}
  ports:
    web:
      nodePort: 30080
    websecure:
      nodePort: 30443
portalIntegration:
  enabled: false
  contentVariant: default
  contentPath: /pm-content.json
  secretResourceDefinition:
    group: v1
    version: v1
    plural: secrets
    singular: secret
    kind: Secret
  image:
    repository: nginx
    tag: '1.25'
    pullPolicy: IfNotPresent
  resources: {}
  ingress:
    annotations: {}
branding:
  sidebar:
    title: LLM by MODEL Corp
