{{- if .Values.portalIntegration.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-portal-integration-providermetadata
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "private-llm-operator.labels" . | nindent 4 }}
    app.kubernetes.io/component: portal-integration
data:
  providermetadata.yaml: |-
{{ (.Files.Get "files/providermetadata.yaml") | indent 4 }}
{{- end }}


