{{- if .Values.portalIntegration.enabled }}
{{- $sidebarTitle := dig "portalIntegration" "sidebar" "title" .Values | default "LLM by MODEL Corp" -}}
{{- $pmContent := .Files.Get "files/pm-content.json" -}}
{{- $pmContent = replace $pmContent "__SIDEBAR_TITLE__" $sidebarTitle -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-portal-integration-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "private-llm-operator.labels" . | nindent 4 }}
    app.kubernetes.io/component: portal-integration
data:
  pm-content.json: |-
{{ $pmContent | indent 4 }}
{{- end }}


