{{- if .Values.portalIntegration.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-portal-integration-contentconfiguration
  {{- $remoteNs := .Values.portalIntegration.kubeconfig.secretNamespace | default .Release.Namespace }}
  namespace: {{ $remoteNs }}
  labels:
    {{- include "private-llm-operator.labels" . | nindent 4 }}
    app.kubernetes.io/component: portal-integration
data:
  contentconfiguration.yaml: |
    apiVersion: ui.platform-mesh.io/v1alpha1
    kind: ContentConfiguration
    metadata:
      labels:
        ui.platform-mesh.io/entity: core_platform-mesh_io_account
        ui.platform-mesh.io/content-for: llm.privatellms.msp
      name: llm-ui
    spec:
      remoteConfiguration:
        url: {{ printf "%s://%s%s" (.Values.PUBLIC_SCHEME | default "http") .Values.PUBLIC_HOST (.Values.portalIntegration.contentPath | default "/pm-content.json") | quote }}
        contentType: json
{{- end }}


