apiVersion: v1
kind: ServiceAccount
metadata:
  name: private-llm-controller-manager
  labels:
    app.kubernetes.io/name: private-llm
{{- if .Values.imagePullSecrets }}
imagePullSecrets:
{{- range .Values.imagePullSecrets }}
  - name: {{ .name }}
{{- end }}
{{- end }}
